---
title: "Chicago R Meetup August 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## R Markdown (See the new [website!](http://rmarkdown.rstudio.com))
  + [Parameterized Reports](http://rmarkdown.rstudio.com/lesson-5.html) - A reusable Stock History Example
  + [Code Folding, Table of Contents](http://rmarkdown.rstudio.com/html_document_format.html) - New components to add to html_document output
  
## R Noteboooks
  + Basic Example of running code chunks with inline output
  + An example using python, R, and [feather](https://blog.rstudio.org/2016/03/29/feather/)
  
  + See the [documentation](http://rmarkdown.rstudio.com/r_notebooks.html) and [webinar](https://www.rstudio.com/resources/webinars/introducing-notebooks-with-r-markdown/)
  
## Sparklyr
  + Example of connecting to a Spark cluster, ETL in dplyr, and fitting a ML model
  + [Website](https://spark.rstudio.com)

## htmlwidgets
  + Code to find and map your nearest Starbucks! 
  + [Website](https://www.htmlwidgets.org)


## Shiny & R Markdown
  + Example of downloading a pdf from R Markdown
  + Example of an [interactive document](http://rmarkdown.rstudio.com/lesson-12.html) using runtime::shiny

## Shing Gadgets / Addins
  + Example of modifying ggplot through a point-and-click addin, [ggThemeAssist](https://github.com/calligross/ggthemeassist)

## flexdashboard
  + Stock price example that lays out htmlwidgets as a dashboard
  + Example of a flexdashboard that incorporates Shiny
  
  + [Website](http://rmarkdown.rstudio.com/flexdashboard/) and [Webinar](https://www.rstudio.com/resources/webinars/introducing-flexdashboards)
  
Please be sure to follow our [blog](https://blog.rstudio.org) or checkout our [webinar](https://www.rstudio.com/resources/webinars) page. If you use R at work and would like to support us or scale R for the enterprise please checkout our [Pro Products](https://www.rstudio.com/pricing) including [RStudio Connect](https://www.rstudio.com/products/connect) our new tool for managing R content, scheduling Rmd reports, and hosting Shiny apps.